version: '3'
services:
  frontend:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile-frontend
    ports:
      - "80:80"
  backend:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile-backend
    ports:
      - "5000:5000"
  db:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile-db
    ports:
      - "5432:5432"

